# Generated by Django 5.2.1 on 2025-06-23 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=100, verbose_name='课程名称')),
                ('course_category', models.CharField(max_length=50, verbose_name='课程大类')),
                ('course_subcategory', models.CharField(max_length=50, verbose_name='课程子类')),
                ('skill', models.CharField(max_length=100, verbose_name='提供技能')),
                ('skill_category', models.CharField(max_length=50, verbose_name='技能大类')),
                ('skill_subcategory', models.CharField(max_length=50, verbose_name='技能子类')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('description', models.TextField(blank=True, verbose_name='详细描述')),
                ('apl_status', models.CharField(blank=True, choices=[('pending', '待处理'), ('approved', '已批准'), ('rejected', '已拒绝'), ('completed', '已完成')], default='pending', max_length=20, verbose_name='申请状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '技能交换申请',
                'verbose_name_plural': '技能交换申请',
                'ordering': ['-created_at'],
            },
        ),
    ]
