# Generated by Django 5.2.1 on 2025-06-25 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_exchangerequest_accepted_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerequest',
            name='apl_status',
            field=models.CharField(blank=True, choices=[('pending', '待处理'), ('waiting', '待回应'), ('rejected', '已拒绝'), ('completed', '已完成'), ('matched', '已匹配')], default='pending', max_length=20, verbose_name='申请状态'),
        ),
    ]
