# Generated by Django 5.2.1 on 2025-06-27 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_alter_exchangerequest_apl_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerequest',
            name='apl_status',
            field=models.CharField(blank=True, choices=[('pending', '待处理'), ('waiting', '待回应'), ('rejected', '已拒绝'), ('completed', '已完成'), ('canceled', '已取消'), ('overdue', '已过期'), ('matched', '已匹配')], default='pending', max_length=20, verbose_name='申请状态'),
        ),
    ]
