# Generated by Django 5.2.1 on 2025-06-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='手机号'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_prefix',
            field=models.CharField(default='+86', max_length=5, verbose_name='国际区号'),
        ),
    ]
